const List<String> countryNames = [
  'Anywhere',
  'United States',
  'United Kingdom',
  'Canada',
  'Australia',
  'Germany',
  'France',
  'Spain',
  'Italy',
  'Japan',
  'South Korea',
  'China',
  'India',
  'Pakistan',
  'Brazil',
  'Mexico',
  'Argentina',
  'Netherlands',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Switzerland',
  'Austria',
  'Belgium',
  'Poland',
  'Czech Republic',
  'Turkey',
  'Russia',
  'South Africa',
  'Egypt',
  'Nigeria',
  'Kenya',
  'Singapore',
  'Malaysia',
  'Indonesia',
  'Thailand',
  'Vietnam',
  'Philippines',
  'New Zealand',
  'Ireland',
  'Portugal',
  'Greece',
  'Bangladesh',
  'Sri Lanka',
  'Nepal',
  'United Arab Emirates',
  'Saudi Arabia',
  'Israel',
  'Jordan',
  'Lebanon',
  'Morocco',
  'Tunisia',
  'Algeria',
  'Ghana',
  'Ethiopia',
  'Tanzania',
  'Uganda',
  'Rwanda',
  'Cameroon',
  'Ivory Coast',
  'Senegal',
  'Mali',
  'Burkina Faso',
  'Chad',
  'Sudan',
  'Libya',
  'Afghanistan',
  'Iran',
  'Iraq',
  'Syria',
  'Yemen',
  'Oman',
  'Qatar',
  'Kuwait',
  'Bahrain',
  'Kazakhstan',
  'Uzbekistan',
  'Turkmenistan',
  'Kyrgyzstan',
  'Tajikistan',
  'Mongolia',
  'Myanmar',
  'Laos',
  'Cambodia',
  'North Korea',
  'Taiwan',
  'Hong Kong',
  'Macau',
  'Colombia',
  'Venezuela',
  'Peru',
  'Chile',
  'Ecuador',
  'Bolivia',
  'Paraguay',
  'Uruguay',
  'Guyana',
  'Suriname',
  'French Guiana',
  'Jamaica',
  'Cuba',
  'Haiti',
  'Dominican Republic',
  'Puerto Rico',
  'Trinidad and Tobago',
  'Barbados',
  'Bahamas',
  'Croatia',
  'Slovenia',
  'Bosnia and Herzegovina',
  'Serbia',
  'Montenegro',
  'Kosovo',
  'North Macedonia',
  'Albania',
  'Bulgaria',
  'Romania',
  'Hungary',
  'Slovakia',
  'Lithuania',
  'Latvia',
  'Estonia',
  'Ukraine',
  'Belarus',
  'Moldova',
  'Georgia',
  'Armenia',
  'Azerbaijan',
  'Cyprus',
  'Malta',
  'Luxembourg',
  'Iceland',
  'Greenland',
  'Faroe Islands',
];

String countryFlag(String country) {
  const flagMap = {
    'Anywhere': '🌍',
    'United States': '🇺🇸',
    'United Kingdom': '🇬🇧',
    'Canada': '🇨🇦',
    'Australia': '🇦🇺',
    'Germany': '🇩🇪',
    'France': '🇫🇷',
    'Spain': '🇪🇸',
    'Italy': '🇮🇹',
    'Japan': '🇯🇵',
    'South Korea': '🇰🇷',
    'China': '🇨🇳',
    'India': '🇮🇳',
    'Pakistan': '🇵🇰',
    'Brazil': '🇧🇷',
    'Mexico': '🇲🇽',
    'Argentina': '🇦🇷',
    'Netherlands': '🇳🇱',
    'Sweden': '🇸🇪',
    'Norway': '🇳🇴',
    'Denmark': '🇩🇰',
    'Finland': '🇫🇮',
    'Switzerland': '🇨🇭',
    'Austria': '🇦🇹',
    'Belgium': '🇧🇪',
    'Poland': '🇵🇱',
    'Czech Republic': '🇨🇿',
    'Turkey': '🇹🇷',
    'Russia': '🇷🇺',
    'South Africa': '🇿🇦',
    'Egypt': '🇪🇬',
    'Nigeria': '🇳🇬',
    'Kenya': '🇰🇪',
    'Singapore': '🇸🇬',
    'Malaysia': '🇲🇾',
    'Indonesia': '🇮🇩',
    'Thailand': '🇹🇭',
    'Vietnam': '🇻🇳',
    'Philippines': '🇵🇭',
    'New Zealand': '🇳🇿',
    'Ireland': '🇮🇪',
    'Portugal': '🇵🇹',
    'Greece': '🇬🇷',
    'Bangladesh': '🇧🇩',
    'Sri Lanka': '🇱🇰',
    'Nepal': '🇳🇵',
    'United Arab Emirates': '🇦🇪',
    'Saudi Arabia': '🇸🇦',
    'Israel': '🇮🇱',
    'Jordan': '🇯🇴',
    'Lebanon': '🇱🇧',
    'Morocco': '🇲🇦',
    'Tunisia': '🇹🇳',
    'Algeria': '🇩🇿',
    'Ghana': '🇬🇭',
    'Ethiopia': '🇪🇹',
    'Tanzania': '🇹🇿',
    'Uganda': '🇺🇬',
    'Rwanda': '🇷🇼',
    'Cameroon': '🇨🇲',
    'Ivory Coast': '🇨🇮',
    'Senegal': '🇸🇳',
    'Mali': '🇲🇱',
    'Burkina Faso': '🇧🇫',
    'Chad': '🇹🇩',
    'Sudan': '🇸🇩',
    'Libya': '🇱🇾',
    'Afghanistan': '🇦🇫',
    'Iran': '🇮🇷',
    'Iraq': '🇮🇶',
    'Syria': '🇸🇾',
    'Yemen': '🇾🇪',
    'Oman': '🇴🇲',
    'Qatar': '🇶🇦',
    'Kuwait': '🇰🇼',
    'Bahrain': '🇧🇭',
    'Kazakhstan': '🇰🇿',
    'Uzbekistan': '🇺🇿',
    'Turkmenistan': '🇹🇲',
    'Kyrgyzstan': '🇰🇬',
    'Tajikistan': '🇹🇯',
    'Mongolia': '🇲🇳',
    'Myanmar': '🇲🇲',
    'Laos': '🇱🇦',
    'Cambodia': '🇰🇭',
    'North Korea': '🇰🇵',
    'Taiwan': '🇹🇼',
    'Hong Kong': '🇭🇰',
    'Macau': '🇲🇴',
    'Colombia': '🇨🇴',
    'Venezuela': '🇻🇪',
    'Peru': '🇵🇪',
    'Chile': '🇨🇱',
    'Ecuador': '🇪🇨',
    'Bolivia': '🇧🇴',
    'Paraguay': '🇵🇾',
    'Uruguay': '🇺🇾',
    'Guyana': '🇬🇾',
    'Suriname': '🇸🇷',
    'French Guiana': '🇬🇫',
    'Jamaica': '🇯🇲',
    'Cuba': '🇨🇺',
    'Haiti': '🇭🇹',
    'Dominican Republic': '🇩🇴',
    'Puerto Rico': '🇵🇷',
    'Trinidad and Tobago': '🇹🇹',
    'Barbados': '🇧🇧',
    'Bahamas': '🇧🇸',
    'Croatia': '🇭🇷',
    'Slovenia': '🇸🇮',
    'Bosnia and Herzegovina': '🇧🇦',
    'Serbia': '🇷🇸',
    'Montenegro': '🇲🇪',
    'Kosovo': '🇽🇰',
    'North Macedonia': '🇲🇰',
    'Albania': '🇦🇱',
    'Bulgaria': '🇧🇬',
    'Romania': '🇷🇴',
    'Hungary': '🇭🇺',
    'Slovakia': '🇸🇰',
    'Lithuania': '🇱🇹',
    'Latvia': '🇱🇻',
    'Estonia': '🇪🇪',
    'Ukraine': '🇺🇦',
    'Belarus': '🇧🇾',
    'Moldova': '🇲🇩',
    'Georgia': '🇬🇪',
    'Armenia': '🇦🇲',
    'Azerbaijan': '🇦🇿',
    'Cyprus': '🇨🇾',
    'Malta': '🇲🇹',
    'Luxembourg': '🇱🇺',
    'Iceland': '🇮🇸',
    'Greenland': '🇬🇱',
    'Faroe Islands': '🇫🇴',
  };
  return flagMap[country] ?? '🌍';
}
